ALTER TABLE bots ADD COLUMN avatar_color TEXT NOT NULL DEFAULT '#8B5CF6';
ALTER TABLE bots ADD COLUMN avatar_shape TEXT NOT NULL DEFAULT 'blob';
ALTER TABLE bots ADD COLUMN tags TEXT[] NOT NULL DEFAULT '{}';
