ALTER TABLE bots ADD COLUMN pinned BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE bots ADD COLUMN hidden BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE bots ADD COLUMN group_name TEXT;
ALTER TABLE bots ADD COLUMN last_read_at TIMESTAMPTZ NOT NULL DEFAULT now();
