import ReactDOM from "react-dom/client";
import "@fontsource/huninn";
import "blobatar/motion.css";
import "blobatar/gaze.css";
import "./styles.css";
import "./refinements.css";
import "./avatar.css";
import "./chat.css";
import "./computer.css";
import "./schedule.css";
import "./call.css";
import "./responsive.css";
import { App } from "./App";
ReactDOM.createRoot(document.getElementById("root")!).render(<App />);
